/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.security.NoSuchAlgorithmException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static main.Gruppe.ps;

/**
 *Die Klasse Regestrierung represntiert eine grphicher benutzeroberfläche
 * in der sich der anwender Regestrieren kann oder zum Login gelangt
 * 
 * @author AAlakdr
 * @version 0.1
 */
public class Registerierung extends javax.swing.JPanel {
 PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form Register
     */
    public Registerierung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameFeld = new javax.swing.JTextField();
        mailFeld = new javax.swing.JTextField();
        passFeld = new javax.swing.JPasswordField();
        rePassFeld = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        anlegen = new javax.swing.JButton();

        setBackground(new java.awt.Color(11, 102, 122));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("E-Mail");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Passwort");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("Passwort wiederholen");

        jButton1.setText("Zurück");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        anlegen.setText("Benutzer anlegen");
        anlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anlegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(anlegen))
                    .addComponent(nameFeld)
                    .addComponent(rePassFeld)
                    .addComponent(passFeld)
                    .addComponent(mailFeld))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePassFeld, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anlegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anlegenActionPerformed
     String query = "SELECT Mail FROM users WHERE Mail =?";
        String name = nameFeld.getText();
        String mail = mailFeld.getText();
        String pass = String.valueOf(passFeld.getPassword());
        String rePass = String.valueOf(rePassFeld.getPassword());
         //frage ob die felder leer sind
        if (Utils.isEmpty(name, mail, pass, rePass)) {
            JOptionPane.showMessageDialog(null, "Es sind nicht alle Felder ausgefüllt");
            return;
         //frage ob der Passwort stimmt nicht mit der RePasswort
        } else if (!pass.equals(rePass)) {
            JOptionPane.showMessageDialog(null, "Passwort stimmt nicht mit der Wiederholung überein");
            return;
        }
        try {
            ps = Utils.getConnection().prepareStatement(query);
            ps.setString(1, mail);
            rs = ps.executeQuery();
            //if der user schon existiert
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "E-Mail existiert bereits");
                return;           
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        String query1 = "INSERT INTO users(Name,Mail,Passwort)VALUES(?,?,?)";
        try {
            ps = Utils.getConnection().prepareStatement(query1);
            ps.setString(1, name);
            ps.setString(2, mail);
            ps.setString(3, Utils.sha256(pass));
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registrierung erfolgreich");
            //wieder zu Login Layout Zurück
            Main.cl.show(Main.cardPanel, "Login");
            //Mach die alle Fielder leer
            nameFeld.setText("");
            mailFeld.setText("");
            rePassFeld.setText("");
            passFeld.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Registrierung nicht erfolgreich");
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Registerierung.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_anlegenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           Main.cl.show(Main.cardPanel, "Login");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anlegen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mailFeld;
    private javax.swing.JTextField nameFeld;
    private javax.swing.JPasswordField passFeld;
    private javax.swing.JPasswordField rePassFeld;
    // End of variables declaration//GEN-END:variables
}
